ET1:
            lat:             (43 + 37. / 60 + 53.0921 / 3600) * np.pi / 180.
            lon:             (10 + 30. / 60 + 16.1878 / 3600) * np.pi / 180.
            opening_angle:   np.pi / 3.
            arm_azimuth:     70.5674 * np.pi / 180. + 2. * k * np.pi / 3.
            psd_data:        'GWFish/detector_psd/ET_psd.txt'
            duty_factor:     0.85
            plotrange:       "3, 3000, 1e-25, 1e-20"
            
ET2:
            lat:             46.5 * np.pi / 180.
            lon:             -119.4 * np.pi / 180.
            opening_angle:   np.pi / 3.
            arm_azimuth:     126. * np.pi / 180.
            psd_data:        'GWFish/detector_psd/ET_psd.txt'
            duty_factor:     0.85
            plotrange:       "3, 3000, 1e-25, 1e-20"
                        
VOH:
            lat:             46.5 * np.pi / 180.
            lon:             -119.4 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     126. * np.pi / 180.
            psd_data:        'GWFish/detector_psd/Voyager_psd.txt'
            duty_factor:     0.85
            plotrange:       "10, 1000, 1e-25, 1e-20"
VOL:
            lat:             30.56 * np.pi / 180.
            lon:             -90.77 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     -197.7 * np.pi / 180.
            psd_data:        'GWFish/detector_psd/Voyager_psd.txt'
            duty_factor:     0.85
            plotrange:       '10, 1000, 1e-25, 1e-20'            
VOI:
            lat:             19.61 * np.pi / 180.
            lon:             77.03 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     100. * np.pi / 180.  # this value is guessed from wikipage
            psd_data:        'GWFish/detector_psd/Voyager_psd.txt'
            duty_factor:     0.85
CE1:
            lat:             46.5 * np.pi / 180.
            lon:             -119.4 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     126. * np.pi / 180.
            psd_data:        'GWFish/detector_psd/CE1_psd.txt'
            duty_factor:     0.85
            plotrange:       '8, 3000, 1e-25, 1e-20'
CE2:
            lat:             46.5 * np.pi / 180.
            lon:             -119.4 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     126. * np.pi / 180.
            psd_data:        'GWFish/detector_psd/CE2_psd.txt'
            duty_factor:     0.85
            plotrange:       '8, 3000, 1e-25, 1e-20'
CEA:
            lat:             -20.517
            lon:             131.061
            opening_angle:   np.pi / 2.
            arm_azimuth:     126. * np.pi / 180.
            psd_data:        'GWFish/detector_psd/CE1_psd.txt'
            duty_factor:     0.85
            plotrange:       '8, 3000, 1e-25, 1e-20'
LLO:
            lat:             30.56 * np.pi / 180.
            lon:             -90.77 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     197.7 * np.pi / 180.
            psd_data:        'GWFish/detector_psd/LIGO_O5_psd.txt'
            duty_factor:     0.85
            plotrange:       10, 1000, 1e-25, 1e-20'
LHO:
            lat:             46.46 * np.pi / 180.
            lon:             -119.4 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     126. * np.pi / 180.
            psd_data:        'GWFish/detector_psd/LIGO_O5_psd.txt'
            duty_factor:     0.85
            plotrange:       '10, 1000, 1e-25, 1e-20'
Vir:
            lat:             43.6 * np.pi / 180.
            lon:             10.5 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     71. * np.pi / 180.
            psd_data:        'GWFish/detector_psd/Virgo_O5_psd.txt'
            duty_factor:     0.85
            plotrange:       10, 1000, 1e-25, 1e-20
KAG:
            lat:             36.41 * np.pi / 180.
            lon:             137.3 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     29.6 * np.pi / 180.
            psd_data:        'GWFish/detector_psd/Kagra_128Mpc_psd.txt'
            duty_factor:     0.85
            plotrange:       [10, 1000, 1e-25, 1e-20]
LIN:
            lat:             19.61 * np.pi / 180.
            lon:             77.03 * np.pi / 180.
            opening_angle:   np.pi / 2.
            arm_azimuth:     100. * np.pi / 180.  # this value is guessed from wikipage
            psd_data:        'GWFish/detector_psd/LIGO_O5_psd.txt'
            duty_factor:     0.85
            plotrange:       '10, 1000, 1e-25, 1e-20'      
            
LGWA:
      k0:           #Shackleton
                    val:           0
                    lat:           -89.9 * np.pi / 180.
                    lon:           '0'
                    hor_direction: np.pi
                    psd_data:      'GWFish/detector_psd/LGWA_psd.txt'
                    duty_factor:   0.7  
      k1:           #de Garlache
                    val:           1
                    lat:           -88.5 * np.pi / 180.
                    lon:           -87.1 * np.pi / 180.
                    hor_direction: np.pi
                    psd_data:      'GWFish/detector_psd/LGWA_psd.txt'
                    duty_factor:   0.7
      k2:           #Shoemaker
                    val:           2
                    lat:           -88.1 * np.pi / 180.
                    lon:           44.9 * np.pi / 180.
                    hor_direction: np.pi
                    psd_data:      'GWFish/detector_psd/LGWA_psd.txt'
                    duty_factor:   0.7
      k3:           #Faustini
                    val:           3
                    lat:           -87.3 * np.pi / 180.
                    lon:           77 * np.pi / 180.
                    hor_direction: np.pi
                    psd_data:      'GWFish/detector_psd/LGWA_psd.txt'
                    duty_factor:   0.7
